sonar.projectKey=Fariguu_Portfolio
sonar.organization=fariguu

# Percorsi sorgenti da analizzare
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Esclusioni per evitare di analizzare artefatti di build o dipendenze
sonar.exclusions=**/.next/**,**/node_modules/**,**/public/**,**/*.config.*,**/*.d.ts
